/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studenthostelmaintenancerequest.trackingsystem.gui.auth;

import java.awt.Component;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import studenthostelmaintenancerequest.trackingsystem.gui.common.CardPanel;
import studenthostelmaintenancerequest.trackingsystem.gui.common.PlaceholderTextField;
import studenthostelmaintenancerequest.trackingsystem.gui.common.UIHelper;

/**
 *
 * @author vian
 */
public class ForgotPasswordFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName());

    private PlaceholderTextField txtEmail;

    public ForgotPasswordFrame() {
        initComponents();
        buildUi();
    }

    private void buildUi() {
        UIHelper.setupAuthFrame(this, "Forgot Password", false);

        CardPanel card = new CardPanel(UIHelper.AUTH_CONTENT_WIDTH);
        JPanel body = card.getBody();

        JLabel lblTitle = UIHelper.createHeaderLabel("Forgot Password", UIHelper.AUTH_CONTENT_WIDTH);
        body.add(lblTitle);
        body.add(Box.createVerticalStrut(12));

        JLabel lblInstruction = UIHelper.createInstructionLabel(
                "Enter your registered email address to verify your account and proceed with password recovery.",
                UIHelper.AUTH_CONTENT_WIDTH);
        body.add(lblInstruction);
        body.add(Box.createVerticalStrut(20));

        txtEmail = UIHelper.createTextField("e.g. studentID@adab.umpsa.edu.my");
        body.add(UIHelper.createFieldGroup(UIHelper.createFieldLabel("Email"), txtEmail));
        body.add(Box.createVerticalStrut(16));

        javax.swing.JButton btnVerify = UIHelper.createPrimaryButton("Verify \u2192");
        btnVerify.addActionListener(e -> UIHelper.navigateTo(this, new setNewPasswordFrame()));
        body.add(btnVerify);
        body.add(Box.createVerticalStrut(16));

        JLabel lblReturn = UIHelper.createHyperlink("\u2190 Return to Login");
        UIHelper.addHyperlinkAction(lblReturn, () -> UIHelper.navigateTo(this, new LoginFrame()));
        body.add(UIHelper.centerHorizontally(lblReturn, UIHelper.FIELD_WIDTH));

        UIHelper.mountFloatingCard(this, card);
        UIHelper.showFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forgot Password");
        setResizable(true);

    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new ForgotPasswordFrame());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
