/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studenthostelmaintenancerequest.trackingsystem.gui.auth;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import studenthostelmaintenancerequest.trackingsystem.gui.common.CardPanel;
import studenthostelmaintenancerequest.trackingsystem.gui.common.PlaceholderTextField;
import studenthostelmaintenancerequest.trackingsystem.gui.common.UIHelper;

/**
 *
 * @author vian
 */
public class ForgotPasswordFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName());

    private PlaceholderTextField txtEmail;

    public ForgotPasswordFrame() {
        initComponents();
        buildUi();
    }

    private void buildUi() {
        UIHelper.setupAuthFrame(this, "Forgot Password", false);

        CardPanel card = new CardPanel();
        card.setLayout(new javax.swing.BoxLayout(card, javax.swing.BoxLayout.Y_AXIS));
        card.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel lblTitle = UIHelper.createHeaderLabel("Forgot Password");
        lblTitle.setAlignmentX(Component.CENTER_ALIGNMENT);
        card.add(lblTitle);
        card.add(Box.createVerticalStrut(20));

        JLabel lblInstruction = UIHelper.createInstructionLabel(
                "Enter your registered email address to verify your account and proceed with password recovery.");
        lblInstruction.setAlignmentX(Component.CENTER_ALIGNMENT);
        card.add(lblInstruction);
        card.add(Box.createVerticalStrut(36));

        JPanel form = new JPanel();
        form.setOpaque(false);
        form.setLayout(new javax.swing.BoxLayout(form, javax.swing.BoxLayout.Y_AXIS));
        form.setAlignmentX(Component.CENTER_ALIGNMENT);
        form.setMaximumSize(new Dimension(UIHelper.FIELD_WIDTH, 400));

        txtEmail = UIHelper.createTextField("e.g. studentID@adab.umpsa.edu.my");
        form.add(UIHelper.createFieldGroup(UIHelper.createFieldLabel("Email"), txtEmail));
        form.add(Box.createVerticalStrut(32));

        javax.swing.JButton btnVerify = UIHelper.createPrimaryButton("Verify \u2192");
        btnVerify.setAlignmentX(Component.LEFT_ALIGNMENT);
        btnVerify.addActionListener(e -> UIHelper.navigateTo(this, new setNewPasswordFrame()));
        form.add(btnVerify);
        form.add(Box.createVerticalStrut(28));

        JLabel lblReturn = UIHelper.createHyperlink("\u2190 Return to Login");
        lblReturn.setAlignmentX(Component.CENTER_ALIGNMENT);
        UIHelper.addHyperlinkAction(lblReturn, () -> UIHelper.navigateTo(this, new LoginFrame()));
        form.add(lblReturn);

        card.add(form);

        JPanel centered = UIHelper.centerCard(card, 680);
        getContentPane().add(centered, new GridBagConstraints());
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forgot Password");
        setPreferredSize(new java.awt.Dimension(1280, 800));
        setResizable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> UIHelper.showFrame(new ForgotPasswordFrame()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
