/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studenthostelmaintenancerequest.trackingsystem.gui.auth;

import studenthostelmaintenancerequest.trackingsystem.gui.common.LoginCardPanel;
import studenthostelmaintenancerequest.trackingsystem.gui.common.PlaceholderPasswordField;
import studenthostelmaintenancerequest.trackingsystem.gui.common.PlaceholderTextField;
import studenthostelmaintenancerequest.trackingsystem.gui.common.UIHelper;

/**
 *
 * @author vian
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    private LoginCardPanel loginCard;

    public LoginFrame() {
        initComponents();
        buildUi();
    }

    private void buildUi() {
        UIHelper.setupAuthFrame(this, "Login", true);

        loginCard = new LoginCardPanel(
                () -> UIHelper.navigateTo(this, new SignUpFrame()),
                () -> UIHelper.navigateTo(this, new ForgotPasswordFrame()),
                () -> {
                    // Backend login logic will be added later.
                });

        UIHelper.mountCenteredCard(this, loginCard);
        UIHelper.showFrame(this);
        getRootPane().setDefaultButton(loginCard.getLoginButton());
    }

    public PlaceholderTextField getEmailField() {
        return loginCard.getEmailField();
    }

    public PlaceholderPasswordField getPasswordField() {
        return loginCard.getPasswordField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        UIHelper.initApplicationLook();
        java.awt.EventQueue.invokeLater(() -> new LoginFrame());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
