/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studenthostelmaintenancerequest.trackingsystem.gui.auth;

import java.awt.Component;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import studenthostelmaintenancerequest.trackingsystem.gui.common.CardPanel;
import studenthostelmaintenancerequest.trackingsystem.gui.common.PlaceholderPasswordField;
import studenthostelmaintenancerequest.trackingsystem.gui.common.UIHelper;

/**
 *
 * @author vian
 */
public class setNewPasswordFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(setNewPasswordFrame.class.getName());

    public setNewPasswordFrame() {
        initComponents();
        buildUi();
    }

    private void buildUi() {
        UIHelper.setupAuthFrame(this, "Set New Password", false);

        CardPanel card = new CardPanel(UIHelper.AUTH_CONTENT_WIDTH);
        JPanel body = card.getBody();

        JLabel lblTitle = UIHelper.createHeaderLabel("Set New Password", UIHelper.AUTH_CONTENT_WIDTH);
        body.add(lblTitle);
        body.add(Box.createVerticalStrut(12));

        JLabel lblInstruction = UIHelper.createInstructionLabel(
                "Please create a new password that you don't use on any other site.",
                UIHelper.AUTH_CONTENT_WIDTH);
        body.add(lblInstruction);
        body.add(Box.createVerticalStrut(20));

        PlaceholderPasswordField txtNewPassword = UIHelper.createPasswordField("Enter new password");
        PlaceholderPasswordField txtConfirmPassword = UIHelper.createPasswordField("Re-enter new password");

        body.add(buildPasswordGroup("New Password", txtNewPassword));
        body.add(Box.createVerticalStrut(14));
        body.add(buildPasswordGroup("Confirm Password", txtConfirmPassword));
        body.add(Box.createVerticalStrut(14));

        JPanel requirements = UIHelper.createRequirementsPanel();
        body.add(requirements);
        body.add(Box.createVerticalStrut(16));

        javax.swing.JButton btnReset = UIHelper.createPrimaryButton("Reset Password");
        btnReset.addActionListener(e -> {
            // Backend reset logic will be added later.
        });
        body.add(btnReset);
        body.add(Box.createVerticalStrut(14));

        JLabel lblReturn = UIHelper.createHyperlink("\u2190 Return to Login");
        UIHelper.addHyperlinkAction(lblReturn, () -> UIHelper.navigateTo(this, new LoginFrame()));
        body.add(UIHelper.centerHorizontally(lblReturn, UIHelper.FIELD_WIDTH));

        UIHelper.mountFloatingCard(this, card);
        UIHelper.showFrame(this);
    }

    private JPanel buildPasswordGroup(String labelText, PlaceholderPasswordField field) {
        JPanel group = new JPanel();
        group.setOpaque(false);
        group.setLayout(new javax.swing.BoxLayout(group, javax.swing.BoxLayout.Y_AXIS));
        group.setAlignmentX(Component.LEFT_ALIGNMENT);
        UIHelper.limitWidth(group, UIHelper.FIELD_WIDTH);

        JLabel label = UIHelper.createFieldLabel(labelText);
        label.setAlignmentX(Component.LEFT_ALIGNMENT);
        group.add(label);
        group.add(Box.createVerticalStrut(6));

        JPanel fieldPanel = UIHelper.createPasswordWithToggle(field);
        fieldPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        group.add(fieldPanel);
        return group;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set New Password");
        setResizable(true);

    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new setNewPasswordFrame());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
