/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studenthostelmaintenancerequest.trackingsystem;

/**
 *
 * @author chaic
 */import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
public class studRHistory extends javax.swing.JFrame {

    // ── Class-level fields for pagination ──────────────────────────
       private List<Object[]> filteredData = new ArrayList<>();
    private int currentPage  = 1;
    private final int rowsPerPage = 3;
    private String filterStatus = "All";
    private String filterType   = "All";
    private final Object[][] allData = {
        {"REQ001", "Electrical",  "8 June 2026", "High",   "IN PROGRESS"},
        {"REQ001", "Furniture",   "8 June 2026", "Medium", "SUBMITTED"},
        {"REQ001", "Plumbing",    "8 June 2026", "Low",    "COMPLETED"},
        {"REQ002", "Air Con",     "7 June 2026", "High",   "IN PROGRESS"},
        {"REQ003", "Electrical",  "6 June 2026", "Medium", "COMPLETED"},
        {"REQ004", "Furniture",   "5 June 2026", "Low",    "SUBMITTED"},
        {"REQ005", "Plumbing",    "4 June 2026", "High",   "COMPLETED"},
        {"REQ006", "Air Con",     "3 June 2026", "Medium", "IN PROGRESS"},
        {"REQ007", "Electrical",  "2 June 2026", "Low",    "SUBMITTED"},
        {"REQ008", "Furniture",   "1 June 2026", "High",   "COMPLETED"},
        {"REQ009", "Plumbing",    "31 May 2026", "Medium", "IN PROGRESS"},
        {"REQ010", "Air Con",     "30 May 2026", "Low",    "SUBMITTED"},
    };
    // ───────────────────────────────────────────────────────────────

    /**
     * Creates new form studRHistory
     */
    public studRHistory() {
         initComponents();
        setupTableStyle();      // 1st: set base style
        setupTableRenderers();  // 2nd: override Priority+Status columns ON TOP
        setupSidebarStyle();
        setupSearch();
        applySearchAndFilter();   // populate on first load
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void applySearchAndFilter() {
        String keyword = jTextField1.getText().trim().toLowerCase();
 
        filteredData = new ArrayList<>();
 
        for (Object[] row : allData) {
            // 1. Keyword: must appear in any column
            boolean keywordMatch = keyword.isEmpty();
            if (!keywordMatch) {
                for (Object cell : row) {
                    if (cell != null && cell.toString().toLowerCase().contains(keyword)) {
                        keywordMatch = true;
                        break;
                    }
                }
            }
            // 2. Status filter (col 4)
            boolean statusMatch = filterStatus.equals("All")
                    || row[4].toString().equalsIgnoreCase(filterStatus);
            // 3. Type filter (col 1)
            boolean typeMatch = filterType.equals("All")
                    || row[1].toString().equalsIgnoreCase(filterType);
 
            if (keywordMatch && statusMatch && typeMatch) {
                filteredData.add(row);
            }
        }
 
        currentPage = 1;   // always restart at page 1 after search/filter
        renderPage();
    }
 
    /** Slices filteredData for the current page and loads it into the table. */
    private void renderPage() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
 
        int total      = filteredData.size();
        int totalPages = Math.max(1, (int) Math.ceil((double) total / rowsPerPage));
 
        // Clamp
        if (currentPage < 1)           currentPage = 1;
        if (currentPage > totalPages)  currentPage = totalPages;
 
        int start = (currentPage - 1) * rowsPerPage;
        int end   = Math.min(start + rowsPerPage, total);
 
        for (int i = start; i < end; i++) {
            model.addRow(filteredData.get(i));
        }
 
        jLabel3.setText(total == 0
            ? "No results found"
            : "Showing " + (start + 1) + " to " + end + " of " + total + " results");
 
        jButton5.setEnabled(currentPage > 1);
        jButton6.setEnabled(currentPage < totalPages);
    }
 
    // ── Wire live search ───────────────────────────────────────────
    private void setupSearch() {
        jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e)  { applySearchAndFilter(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e)  { applySearchAndFilter(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { applySearchAndFilter(); }
        });
    }
 
    // ── Filter dialog ──────────────────────────────────────────────
    private void showFilterDialog() {
        String[] statusOptions = {"All", "IN PROGRESS", "SUBMITTED", "COMPLETED"};
        String[] typeOptions   = {"All", "Electrical", "Plumbing", "Furniture", "Air Con"};
 
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(2, 2, 8, 8));
        javax.swing.JComboBox<String> statusCombo = new javax.swing.JComboBox<>(statusOptions);
        javax.swing.JComboBox<String> typeCombo   = new javax.swing.JComboBox<>(typeOptions);
        statusCombo.setSelectedItem(filterStatus);
        typeCombo.setSelectedItem(filterType);
        panel.add(new javax.swing.JLabel("Status:"));       panel.add(statusCombo);
        panel.add(new javax.swing.JLabel("Request Type:")); panel.add(typeCombo);
 
        int result = JOptionPane.showConfirmDialog(this, panel,
            "Filter Requests", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
 
        if (result == JOptionPane.OK_OPTION) {
            filterStatus = (String) statusCombo.getSelectedItem();
            filterType   = (String) typeCombo.getSelectedItem();
 
            boolean active = !filterStatus.equals("All") || !filterType.equals("All");
            jButton7.setText(active ? "Filter ✓🔽" : "Filter🔽");
            jButton7.setForeground(active ? new Color(0, 120, 120) : Color.BLACK);
 
            applySearchAndFilter();   // re-scan all 12 rows with new filter
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("View Request History");

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(210, 210, 210));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Maintenance Request History");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Request Type", "Date Raised", "Priority", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(">");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jButton7.setBackground(new java.awt.Color(245, 245, 245));
        jButton7.setText("Filter🔽");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(36, 36, 36))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jLabel3))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        jButton3.setText("View Request History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setLabel("Submit Maintenance Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Darshboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addGap(37, 37, 37))
        );

        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setText("Student Hostel Maintenance Request & Tracking System");

        jButton4.setText("Alex Johnson ▾ STUDENT");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new studRHistory().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
new SubmitMRequest().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Popup Menu
        // Create popup menu
        JPopupMenu userDropdown = new JPopupMenu();

        // Create Log Out menu item
        JMenuItem logoutItem = new JMenuItem("🔓 Log Out");
        logoutItem.setFont(new Font("Arial", Font.PLAIN, 13));
        logoutItem.setForeground(Color.RED);
        userDropdown.add(logoutItem);

        // Log out action
        logoutItem.addActionListener(e -> {
            int confirm = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to log out?",
                "Log Out",
                JOptionPane.YES_NO_OPTION
            );
            if (confirm == JOptionPane.YES_OPTION) {
                dispose();
                // new LoginForm().setVisible(true); // uncomment when LoginForm exists
            }
        });

        // Show dropdown BELOW the button
        userDropdown.show(jButton4, 0, jButton4.getHeight());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (currentPage > 1) {
            currentPage--;
            loadPage(currentPage);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       int totalPages = (int) Math.ceil((double) allData.length / rowsPerPage);
    if (currentPage < totalPages) {
        currentPage++;
        loadPage(currentPage);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new stdDarshboard().setVisible(true);
    this.dispose();
    

            
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        // Status options
    String[] statusOptions = {"All", "IN PROGRESS", "SUBMITTED", "COMPLETED", "CANCELLED"};
    // Request Type options
    String[] typeOptions   = {"All", "Electrical", "Plumbing", "Furniture", "Air Con"};

    // Build dialog panel
    javax.swing.JPanel filterPanel = new javax.swing.JPanel(new java.awt.GridLayout(4, 2, 8, 8));

    javax.swing.JLabel statusLabel = new javax.swing.JLabel("Status:");
    javax.swing.JComboBox<String> statusCombo =
        new javax.swing.JComboBox<>(statusOptions);
    statusCombo.setSelectedItem(filterStatus);

    javax.swing.JLabel typeLabel = new javax.swing.JLabel("Request Type:");
    javax.swing.JComboBox<String> typeCombo =
        new javax.swing.JComboBox<>(typeOptions);
    typeCombo.setSelectedItem(filterType);

    filterPanel.add(statusLabel);
    filterPanel.add(statusCombo);
    filterPanel.add(typeLabel);
    filterPanel.add(typeCombo);

    int result = JOptionPane.showConfirmDialog(
        this, filterPanel,
        "Filter Requests",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE
    );

    if (result == JOptionPane.OK_OPTION) {
        filterStatus = (String) statusCombo.getSelectedItem();
        filterType   = (String) typeCombo.getSelectedItem();
        applyFilter();

        // Update button to show active filter
        if (filterStatus.equals("All") && filterType.equals("All")) {
            jButton7.setText("▼ Filter");
            jButton7.setForeground(java.awt.Color.BLACK);
        } else {
            jButton7.setText("▼ Filter ✓");
            jButton7.setForeground(new java.awt.Color(0, 120, 120));
        }
    }
}

private void applyFilter() {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter =
        new javax.swing.table.TableRowSorter<>(model);
    jTable1.setRowSorter(sorter);

    // Build combined filter for Status (col 4) and Type (col 1)
    java.util.List<javax.swing.RowFilter<Object, Object>> filters = new java.util.ArrayList<>();

    if (!filterStatus.equals("All")) {
        filters.add(javax.swing.RowFilter.regexFilter(
            "(?i)^" + filterStatus + "$", 4));
    }
    if (!filterType.equals("All")) {
        filters.add(javax.swing.RowFilter.regexFilter(
            "(?i)^" + filterType + "$", 1));
    }

    if (filters.isEmpty()) {
        sorter.setRowFilter(null);
    } else {
        sorter.setRowFilter(javax.swing.RowFilter.andFilter(filters));
    }
    }//GEN-LAST:event_jButton7ActionPerformed
 

// ── Pagination ─────────────────────────────────────────────────
    
    private void loadPage(int page) {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        int start = (page - 1) * rowsPerPage;
        int end   = Math.min(start + rowsPerPage, allData.length);

        for (int i = start; i < end; i++) {
            model.addRow(allData[i]);
        }

        // FIX: use jLabel3 (jLabel9 does not exist in this form)
        jLabel3.setText("Showing " + (start + 1) + " to " + end +
                        " of " + allData.length + " results");
    }

    
    
    

  // ── Table base style (call BEFORE renderers) ──────────────────
    private void setupTableStyle() {
        jTable1.setRowHeight(28);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable1.getTableHeader().setBackground(new java.awt.Color(220, 220, 220));
        jTable1.getTableHeader().setForeground(java.awt.Color.BLACK);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(new java.awt.Color(220, 220, 220));
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(110);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(110);
    }

    // ── Color renderers (call AFTER setupTableStyle) ──────────────
    private void setupTableRenderers() {
        // Priority column (index 3)
        jTable1.getColumnModel().getColumn(3).setCellRenderer(
            new javax.swing.table.DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(
                        javax.swing.JTable table, Object value,
                        boolean isSelected, boolean hasFocus, int row, int col) {
                    javax.swing.JLabel label = (javax.swing.JLabel)
                        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
                    label.setOpaque(true);
                    label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    label.setFont(label.getFont().deriveFont(java.awt.Font.BOLD));
                    if (value != null) {
                        switch (value.toString()) {
                            case "High":
                                label.setBackground(new java.awt.Color(255, 99, 99));
                                label.setForeground(java.awt.Color.WHITE); break;
                            case "Medium":
                                label.setBackground(new java.awt.Color(255, 180, 80));
                                label.setForeground(java.awt.Color.WHITE); break;
                            case "Low":
                                label.setBackground(java.awt.Color.WHITE);
                                label.setForeground(java.awt.Color.DARK_GRAY); break;
                            default:
                                label.setBackground(java.awt.Color.WHITE);
                                label.setForeground(java.awt.Color.BLACK);
                        }
                    }
                    return label;
                }
            }
        );

        // Status column (index 4)
        jTable1.getColumnModel().getColumn(4).setCellRenderer(
            new javax.swing.table.DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(
                        javax.swing.JTable table, Object value,
                        boolean isSelected, boolean hasFocus, int row, int col) {
                    javax.swing.JLabel label = (javax.swing.JLabel)
                        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
                    label.setOpaque(true);
                    label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    label.setFont(label.getFont().deriveFont(java.awt.Font.BOLD));
                    if (value != null) {
                        switch (value.toString()) {
                            case "IN PROGRESS":
                                label.setBackground(new java.awt.Color(255, 165, 80));
                                label.setForeground(java.awt.Color.WHITE); break;
                            case "SUBMITTED":
                                label.setBackground(new java.awt.Color(0, 188, 212));
                                label.setForeground(java.awt.Color.WHITE); break;
                            case "COMPLETED":
                                label.setBackground(new java.awt.Color(76, 175, 80));
                                label.setForeground(java.awt.Color.WHITE); break;
                            default:
                                label.setBackground(java.awt.Color.WHITE);
                                label.setForeground(java.awt.Color.BLACK);
                        }
                    }
                    return label;
                }
            }
        );
    }

    

    // ── Sidebar style ─────────────────────────────────────────────
    private void setupSidebarStyle() {
        java.awt.Color defaultBg = new java.awt.Color(245, 245, 245);
        java.awt.Color activeBg  = new java.awt.Color(204, 229, 229);
        for (javax.swing.JButton btn : new javax.swing.JButton[]{jButton1, jButton2, jButton3}) {
            btn.setContentAreaFilled(true);
            btn.setBackground(defaultBg);
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            btn.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        }
        jButton3.setBackground(activeBg);
        jButton3.setFont(new Font("Segoe UI", Font.BOLD, 12));
    }

    // ── Main ──────────────────────────────────────────────────────
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException |
                 IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studRHistory.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new studRHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
